### ISSUE TITLE
Verkar inte fungera längre?

### ISSUE THREAD

**Issue by krissen** [osund/urget#1]
Testade, men får en undertext-fil och en 56k stor "mp4"-fil.

**Comment by osund** [comment]
Vilken URL har videoklippet du testar med? Ser ut att fungera för mig fortfarande då jag testar det exempel jag gett i alla fall, dvs

	$ wget "https://github.com/osund/urget/raw/master/urget.py"
	$ python3 urget.py http://urplay.se/Produkter/180680-De-obekvama-Peter-Sunde

Men verkar som det funkar dåligt då jag testar med andra URL:er. Lägger man till --json får man en utskrift som kanske kan hjälpa för att se vad som går fel eller i alla fall vilka format som finns.

	$ python3 urget.py --json http://urplay.se/Produkter/180680-De-obekvama-Peter-Sunde

**Comment by krissen** [comment]
Hmm. Har senaste från git.

Då leder `urget.py http://urplay.se/Produkter/186587-Livet-i-Bokstavslandet-Skonhet` till två filer. En `.tt` på 25K och en `.mp4` på 52K.

Kör jag med `--json` får jag däremot nog något som verkar vettigt, nämligen:

```
$ urget.py --json http://urplay.se/Produkter/186587-Livet-i-Bokstavslandet-Skonhet                                                                              
------
UR Get
------
{
    "file_flash": "186000-186999/186587-19.mp4",
    "file_hd": "186000-186999/186587-7.mp4",
    "file_html5": "urplay/_definst_/mp4:186000-186999/186587-13.mp4/",
    "file_html5_hd": "urplay/_definst_/mp4:186000-186999/186587-14.mp4/",
    "file_mobile": "186000-186999/186587-17.mp4",
    "id": 186587,
    "image": "http://assets.ur.se/id/186587/images/1_l.jpg",
    "only_in_sweden": false,
    "product_type": "programtv",
    "series_id": 186586,
    "series_title": "Livet i Bokstavslandet",
    "skin": "/design/ur_play/javascript/jwplayer/skins/urplay/urplay.zip",
    "streamable": true,
    "streaming_config": {
        "http_streaming": {
            "hds_file": "manifest.f4m",
            "hls_file": "playlist.m3u8",
            "smooth_file": "Manifest"
        },
        "loadbalancer": "http://130.242.59.74/loadbalancer.json",
        "rtmp": {
            "application": "urplay"
        },
        "streamer": {
            "geoip_country_code": "SE",
            "redirect": "130.242.59.75"
        },
        "tt_subtitles": {
            "base_uri": "http://undertexter.ur.se/"
        }
    },
    "subtitle_default": "Svenska",
    "subtitle_labels": "Svenska",
    "subtitles": "http://undertexter.ur.se/186000-186999/186587-9.tt",
    "title": "Livet i Bokstavslandet : Sk\u00f6nhet"
}
```

Den 52K stora `.mp4`-filen jag nämnde är `186587-7.mp4`. Filnamnet hittas ovan. Men... Ja. Det blir alltså inte riktigt rätt. Borde den ladda ner html_hd istället eller något, tro? Eller har den fått `file_hd` om bakfoten?

Länken du nämnde (`...Peter-Sunde`) funkar dock fint här med. Då laddar den ner videofil.

**Comment by osund** [comment]
Ändrade lite nu och la till stöd för att ange --quality. Så om du laddar ner den nya versionen av skriptet och kör

	$ python3 urget.py --quality hd http://urplay.se/Produkter/186587-Livet-i-Bokstavslandet-Skonhet

borde det fungera. Trots att jag fick utskrifter i stil med

	[hls,applehttp @ 0xxxxxxxxxxxxx] Invalid timestamps stream
	[mp4 @ 0xxxxxxxxxxxxx] Invalid DTS: [...] PTS: [...] in output stream 0:0, replacing by guess

verkade MP4-filen vara helt okej.

**Comment by osund** [comment]
Fast upptäckte att det funkade även med gamla versionen av skriptet för mig (med ditt exempel). Kan det vara problem med din version av ffmpeg?

Så här ser det ut för mig (dvs väldigt nyligen kompilerad):

	$ ffmpeg -version
	ffmpeg version 2.5.4 Copyright (c) 2000-2015 the FFmpeg developers
	built on Feb 13 2015 17:05:44 with gcc 4.9.2 (GCC) 20150204 (prerelease)

**Comment by krissen** [comment]
Provade med den nya versionen, men resulterade i samma 52k fil. Möjligt det är ffmpeg som det handlar om; har en avsevärt äldre version: 1.2.6. Försöker med nyare och återkommer!

**Comment by krissen** [comment]
Du hade helt rätt! Fungerade med ffmpeg v 2.6. (Provade inte med versioner där emellan, så vet inte var den avgörande ändringen gjorts.)

**Comment by krissen** [comment]
Från det ena till det helt andra (skriver här för jag såg inget forum), finns det fler switches än vad `--help` skildrar? Tänker t ex på output till stdout eller annat filnamn --- exempelvis så att kunna döpa till `title` som den ju uppenbarligen ändå känner till (enligt `json`).

**Comment by osund** [comment]
Nej, det finns inga andra än de du får när du skriver `--help`. Skriptet är ju rätt litet och var inte medveten om någon annan än jag själv använt det förrän du skrev här. Kul att det kommer till användning. Du får gärna komma med fler förslag om det är något annat du vill ha ändrat.

Senaste versionen jag nyss la upp använder titeln som filnamn. Vill man ha tillbaka det gamla beteendet av någon anledning (att det kraschar pga något specialtecken kanske), går det med `--rawtitle`.

**Comment by krissen** [comment]
Gott! Tack för det (titeln).
